version: '3.8'

services:
  app:
    container_name: app
    build: ../
    ports:
      - "3000:3000"
    env_file:
      - ../env/.env
    depends_on:
      - mongodb
      - rabbitmq
    volumes:
      - ../app:/app/app
      - ../app/templates/:/app/templates
      
  mongodb: 
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    env_file:
      - ../env/.env
    volumes:
      - ../mongodata:/data/db

  celery_worker:
    container_name: celery_worker
    build: ../
    env_file:
      - ../env/.env
    command: celery -A app.config.celery worker --loglevel=info
    volumes:
      - ../app:/app/app
    depends_on:
      - app
      - rabbitmq

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ../env/.env
    volumes:
      - ../rabbitmqdata:/var/lib/rabbitmq

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
